//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_Auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        public int ProID { get; set; }
        public string ProName { get; set; }
        public string FullDes { get; set; }
        public decimal PriceStarting { get; set; }
        public decimal PriceBuy { get; set; }
        public int CatID { get; set; }
        public decimal PriceHighest { get; set; }
        public int Customer { get; set; }
        public System.DateTime TimeStart { get; set; }
        public System.DateTime TimeEnd { get; set; }
        public bool Adjourning { get; set; }
        public bool Status { get; set; }
        public int Required { get; set; }
        public decimal Step { get; set; }
        public int Seller { get; set; }
        public int Quantity { get; set; }
        public decimal PriceCurrent { get; set; }
    }
}
