//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_Auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ID { get; set; }
        public int ProID { get; set; }
        public int Reviewer { get; set; }
        public bool Type { get; set; }
        public string Comment { get; set; }
        public int Receiver { get; set; }
    }
}
